using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace PE.Probs
{
    public class Problem2
    {
            //  Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
            //  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
            //  By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


        public int EvenFinonacciNumbers(int Number1, int Number2, int donotexceed)
        {

            int sum = 0;

            int num1 = Number1;
            int num2 = Number2;

            bool finished = false;

            while (!finished)
            {
                int NextNum = num1 + num2;

                if (NextNum < donotexceed)
                {

                    if (NextNum % 3 == 0)
                    {
                        sum += NextNum;
                    }

                    num1 = num2;
                    num2 = NextNum;
                }
                else
                {
                    finished = true;
                }


            }

            return sum;
        }
    }
}
